# Generated by Django 2.1.1 on 2018-09-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Equipos',
        ),
    ]
